---
title: <center><font size="6"><b>Tree estimation with Revbayes</b></font></center>
subtitle: <center><font size="4"><b>Long-billed hermit song cultural evolution</b></font></center>
author: <center><font size="4"><a href="http://marceloarayasalas.weebly.com/">Marcelo Araya-Salas, PhD</a></font></center>
date: <center>`r format(Sys.Date(), "%d-%m-%Y")`</center>
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: no
fontsize: 12pt 
editor_options: 
  chunk_output_type: console
---

## Selecting leks for analysis
```{r selecting leks}

dat <- read.csv("./data/raw/segments_by_song_type.csv", stringsAsFactors = FALSE)

yrs <- read.csv("./data/raw/year_range_by_song_type.csv", stringsAsFactors = FALSE)

print("song types per lek")
stl <- tapply(dat$song.type, dat$lek, length)

print("year per lek")
ypl <- tapply(yrs$year, yrs$lek, function(x) length(unique(x)))

print("year range per lek")
yrpl <- tapply(yrs$year, yrs$lek, function(x) max(x) - min(x))

print("year range per lek")
gpl <- yrpl - ypl + 1
set.seed(1011)
rnd_var <- rnorm(n = length(stl), mean = 2, sd = 1)

cols <- rep("white", length(gpl))
cols[which(names(gpl) %in%  c("SUR", "CCE", "HC1", "BR1", "TR1"))] <- viridis::viridis(10, alpha = 0.5)[3]

plot(stl, ypl + rnd_var, col = cols, xlab = "# of song types", ylab = "# of years sampled", pch = 20, cex = 9)
text(stl, ypl+ rnd_var, labels = names(stl), cex = 2)

plot(stl, yrpl+ rnd_var, col = cols, cex = 9, pch = 20, xlab = "# of song types", ylab = "year range")
text(stl, yrpl+ rnd_var, labels = names(stl), cex = 2)

plot(gpl, yrpl+  rnd_var, col = cols, cex = 9, pch = 20, xlab = "# of year gaps", ylab = "year range")
text(gpl, yrpl+ rnd_var, labels = names(stl), cex = 2)


#selected leks
sel_leks <- c("SUR", "CCE", "HC1", "BR1", "TR1")

```



```{r revbayes loop, eval = FALSE, echo = TRUE}

yrs$song.type.year <- paste(yrs$song.type, yrs$year, sep = "-")

alignment	<- c("optimal", "all.equal", "prank") # ER = equal rates

# use all fosils (e.g. SURA-2011, SURA-2012, )
use_all_fossils <- c("all", "early")

# include also fossils before 2008
use_old_fossils <-  c("old", "new")


# create taxa tsv files for revBayes
out <- lapply(unique(leks), function(x)
{
  
  X <- yrs[yrs$lek == x, ]
  X$taxon <- X$song.type.year
  
  X$max <- X$min <- max(X$year) - X$year
  
  # all fossils including before 2008
  all.old <- X <- X[order(X$song.type, X$year), ]
  
  write.table(all.old[, c("taxon", "min", "max")], file = paste0("./data/processed/revBayes/fossils/", x, "_taxa_all_old.tsv"),  sep = "\t", quote = FALSE, row.names = FALSE)

  # only first appearance of song type/fossil including before 2008   
  early.old <- X[!duplicated(X$song.type), ]
  
  write.table(early.old[, c("taxon", "min", "max")], file = paste0("./data/processed/revBayes/fossils/", x,  "_taxa_early_old.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)

  
  Y <- X[X$year > 2007, ] 
  Y <- Y[order(Y$song.type, Y$year), ]
  
  # all fossils excluding before 2008
  all.new <- Y
  
    write.table(all.new[, c("taxon", "min", "max")], file = paste0("./data/processed/revBayes/fossils/", x,  "_taxa_all_new.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)


  # only first appearance of song type/fossil including before 2008   
  early.new <- Y[!duplicated(Y$song.type), ]
  
  write.table(early.new[, c("taxon", "min", "max")], file = paste0("./data/processed/revBayes/fossils/", x,  "_taxa_early_new.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)

  
} )

# make all possible combinations
grd <- expand.grid(lek = sel_leks, alignment = alignment, use_old_fossils = use_old_fossils, use_all_fossils = use_all_fossils)

templ <- readLines("./source/template.Rev")

algs <- list.files(path = "./data/processed/nexus", pattern = "\\.nex$")

# algs <- grep(pattern = "optimal", algs, value = TRUE)

grd <- grd[order(grd$lek), ]

# remove leks with output
current.output <- list.files(pattern = "log$|trees$", path = "./output/revbayes", recursive = TRUE)

done.leks <- unique(substr(current.output, start = 0, 3))

grd <- grd[!(grd$lek %in% done.leks & grd$alignment != "prank"), ]

nrow(grd)

out <- pblapply(1:nrow(grd), cl = 4, function(x){
  
  yrs.lek <- yrs[yrs$lek == grd$lek[x],]
  last.year.songs <- yrs.lek$song.type.year[yrs.lek$year == max(yrs.lek$year)]
  
  last.year.songs <- paste0(paste0('"', last.year.songs), '"')
  
  last.year.songs <- paste0("clade(", paste0(last.year.songs, collapse = ", "), ")")
  
 nx <- paste0("./data/processed/nexus/", grd$lek[x], "_", grd$alignment[x], "_", grd$use_all_fossils[x], "_", grd$use_old_fossils[x], "_alignment.nex")
  
  tsv <- paste0("./data/processed/revBayes/fossils/", grd$lek[x], "_taxa_", grd$use_all_fossils[x], "_", grd$use_old_fossils[x], ".tsv")
  
    templ <- readLines("./source/template.Rev")

    templ[1] <- gsub("aligment.name", nx, templ[1])
    templ[2] <- gsub("tsv.file", tsv, templ[2])
    templ[7] <- gsub("LAST.SONG.TYPES", last.year.songs, templ[7])
    
    
    fl.nm.rb <- paste0("./source/", grd$lek[x], "_", grd$use_all_fossils[x], "_", grd$use_old_fossils[x],".Rev")
     
    writeLines(templ, con = fl.nm.rb)

    # cll <- paste0("~/Downloads/revbayes/projects/cmake/rb ", fl.nm.rb)
    cll <- paste0("~/Documents/Marcelo/song_alignment/boost_1_71_0/revbayes/projects/cmake/rb ", fl.nm.rb) 
    
     system(cll,  show.output.on.console = FALSE)

    # copy ouput files to  /output/revbayes/
      new.output <- list.files(pattern = "log$|trees$", recursive = TRUE)
    
    copied.output <- list.files(pattern = "log$|trees$", path = "./output/revbayes/", recursive = TRUE)
    
    new.output <- new.output[!basename(new.output) %in% copied.output]
    
    if (length(new.output > 0))
    file.copy(from = output, to =file.path("./output/revbayes/", basename(output)))

})

  
```

---

<font size="4">R session information</font>

```{r session info, echo=F}

sessionInfo()

```
